swagger: "2.0"
info:
  title: "Contacts API"
  description: "A simple API that allows users to create, read, update, and delete contacts."
  version: "1.0.0"
# This field will be replaced by the deploy_api.sh script.
host: "dauntless-arc-398505.appspot.com"
schemes:
  - "https"
paths:
  "/contacts":
    get:
      description: "Get a list of all contacts."
      operationId: "GET-contacts"
      responses:
        200:
          description: "Success!"
          schema:
            type: array
            $ref: "#/definitions/Contact"
        400:
          description: "Resource /contacts couldn't been found!"
    post:
      description: "Creates a new contact"
      operationId: "GET-contact"
      parameters:
        - name: contact
          in: body
          description: "Contact to add to the store"
          required: true
          schema:
            $ref: "#/definitions/NewContact"
      responses:
        "200":
          description: "Contact response"
          schema:
            $ref: "#/definitions/Contact"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"

  "/contacts/{id}":
    get:
      description: Returns a contact based on a single ID
      operationId: "GET-contact-id"
      parameters:
        - name: id
          in: path
          description: ID of contact to fetch
          required: true
          type: string
          format: string
        - name: contact
          in: body
          description: "Contact to add to the store"
          required: true
          schema:
            $ref: "#/definitions/Contact"
      responses:
        200:
          description: "Success!"
          schema:
            $ref: "#/definitions/Contact"
        400:
          description: "Resource /contacts/:id couldn't been found!"
    put:
      description: Updates a single contact based on the ID supplied
      operationId: "PUT-contact-id"
      parameters:
        - name: id
          in: path
          description: ID of contact to fetch
          required: true
          type: string
          format: string
      responses:
        204:
          description: contact updated
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"
    delete:
      description: deletes a single contact based on the ID supplied
      operationId: "DELETE-contact-id"
      parameters:
        - name: id
          in: path
          description: ID of contact to delete
          required: true
          type: string
      responses:
        "204":
          description: contact deleted
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/Error"

definitions:
  Contact:
    allOf:
      - $ref: "#/definitions/NewContact"
      - required:
          - id
        type: object
        properties:
          id:
            type: string
            description: contact id

  NewContact:
    type: object
    title: Contact
    properties:
      name:
        type: string
        description: contact's name
      email:
        type: string
        description: contact's email
      phone:
        type: string
        description: contact's phone
      notes:
        type: string
        description: contact's notes

  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
